sonar.projectKey=meyer-pidiache_sortcrab
sonar.organization=meyer-pidiache

sonar.projectName=sortcrab
sonar.projectVersion=0.1.2

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.language=rust

sonar.coverageReportPaths=sonarqube-coverage.xml
sonar.rust.clippy.reportPaths=clippy_report.json
